ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WEEK_CLOSED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SAVING_GOAL_REACHED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LOW_STOCK';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BUDGET_ALERT';
